### ISSUE TITLE
Missing copyright and license information

### ISSUE THREAD

**Issue by mutability** [ntosis/GUI_dump1090#1]
Much of the code in mainwindow.\* appears to have been copied from one version of dump1090 or another (probably antirez's version, I think), but the copyright and license information have been stripped.

Please restore the copyright & license headers.

**Comment by ntosis** [comment]
Yes, this is only a GUI for Dump1090, the program is the dump1090.

**Comment by mutability** [comment]
I understand that. But you have taken the dump1090 code and removed the license and copyright information.

The license of the dump1090 code requires that, if you want to modify or redistribute the code, you must do certain things such as retain the license and copyright information. If you do not follow those conditions, you may not modify and redistribute the code.

So, could you please restore the license and copyright information, or remove your copy of the code, please?

**Comment by ntosis** [comment]
ok, thank you, i have written an email to the Salvatore Sanfilippo and i am waiting the response to update the license.

**Comment by ntosis** [comment]
license updated
